.TH "src/divide_and_conquer.cpp" 3 "Thu Mar 12 2020" "Version 1" "DAA Assignment - 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/divide_and_conquer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph1\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBN\fP   1000"
.br
.ti -1c
.RI "#define \fBll\fP   long long"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDCSC\fP (\fBGraph1\fP g)"
.br
.RI "This is the core function of the Divide and Conquer Algorithm to find Strongly Connected Components\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "This is the main function of this c++ program\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unordered_map< int, list< int > > \fBadj\fP"
.br
.RI "This Program is the Implementation of \fBDivide_and_Conquer Algorithm\fP presented in the research paper\&. "
.ti -1c
.RI "unordered_map< int, list< int > > \fBrev_adj\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ll   long long"

.PP
Definition at line 7 of file divide_and_conquer\&.cpp\&.
.SS "#define N   1000"

.PP
Definition at line 6 of file divide_and_conquer\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void DCSC (\fBGraph1\fP g)"

.PP
This is the core function of the Divide and Conquer Algorithm to find Strongly Connected Components\&. ### Algorithm 
.PP
.nf
DCSC(G)
    If G has no edges then
        forall v in V Output {v}\&.
    Else
        Select a random vertex v from V
        SCC <- Pred(G, v) \ Desc(G, v)
        Output SCC
        DCSC(Pred(G, v) \ SCC)
        DCSC(Desc(G, v) \ SCC)
        DCSC(Rem(G, v))

.fi
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIg\fP : \fBGraph1\fP on which the algorithm is to be applied 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing is returned 
.RE
.PP
\fBSee also:\fP
.RS 4
getPred() getDesc() \fBmain()\fP 
.RE
.PP

.PP
Definition at line 157 of file divide_and_conquer\&.cpp\&.
.SS "int main ()"

.PP
This is the main function of this c++ program\&. A \fBGraph1\fP object is created using data from input and the function DCSC is called on this \fBGraph1\fP\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBDCSC()\fP 
.RE
.PP
\fBNote:\fP
.RS 4
This is the main function 
.RE
.PP

.PP
Definition at line 200 of file divide_and_conquer\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "unordered_map<int, list<int> > adj"

.PP
This Program is the Implementation of \fBDivide_and_Conquer Algorithm\fP presented in the research paper\&. We use DCSC, predecesser,descendent methods to find the \fBStroingly Connected Components\fP\&. 
.PP
Definition at line 13 of file divide_and_conquer\&.cpp\&.
.SS "unordered_map<int, list<int> > rev_adj"

.PP
Definition at line 14 of file divide_and_conquer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment - 1 from the source code\&.
