.TH "graphing" 3 "Tue Apr 21 2020" "DAA Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphing
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdataset_name\fP = sys\&.argv[1]\&.split('/')[\-1][:\-4]"
.br
.ti -1c
.RI "\fBDG\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBv\fP"
.br
.ti -1c
.RI "\fBe\fP"
.br
.ti -1c
.RI "\fBline\fP = edges_file\&.readline()"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBshape\fP = nx\&.spring_layout(\fBDG\fP)"
.br
.ti -1c
.RI "dictionary \fBoptions\fP"
.br
.ti -1c
.RI "\fBpos\fP"
.br
.ti -1c
.RI "\fBcomp_graph\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBcolors\fP = np\&.array([])"
.br
.ti -1c
.RI "int \fBc\fP = 0"
.br
.ti -1c
.RI "\fBs\fP = scc\&.readlines()"
.br
.ti -1c
.RI "\fBV\fP = list(map(int, line\&.split()))"
.br
.ti -1c
.RI "\fBsub\fP = DG\&.subgraph(\fBV\fP)"
.br
.ti -1c
.RI "\fBcmap\fP"
.br
.ti -1c
.RI "\fBnode_color\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int graphing\&.c = 0"

.SS "graphing\&.cmap"

.SS "graphing\&.colors = np\&.array([])"

.SS "graphing\&.comp_graph = nx\&.DiGraph()"

.SS "graphing\&.dataset_name = sys\&.argv[1]\&.split('/')[\-1][:\-4]"

.SS "graphing\&.DG = nx\&.DiGraph()"

.SS "graphing\&.e"

.SS "graphing\&.line = edges_file\&.readline()"

.SS "graphing\&.node_color"

.SS "dictionary graphing\&.options"
\fBInitial value:\fP
.PP
.nf
1 =  {
2     'node_size': 20,
3     'width': 0\&.1,
4     'font_size':10,
5     'alpha':0\&.6,
6     'edge_color': '#555555',
7 }
.fi
.SS "graphing\&.pos"

.SS "graphing\&.s = scc\&.readlines()"

.SS "graphing\&.shape = nx\&.spring_layout(\fBDG\fP)"

.SS "graphing\&.sub = DG\&.subgraph(\fBV\fP)"

.SS "graphing\&.v"

.SS "graphing\&.V = list(map(int, line\&.split()))"

.SS "graphing\&.x"

.SS "graphing\&.y"

.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment 1 from the source code\&.
