.TH "E:/Projects/DAA_Assignments/assign1/src/graphing.py" 3 "Fri Mar 13 2020" "DAA Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Projects/DAA_Assignments/assign1/src/graphing.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgraphing\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgraphing\&.dataset_name\fP = sys\&.argv[1]\&.split('/')[\-1][:\-4]"
.br
.ti -1c
.RI "\fBgraphing\&.DG\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBgraphing\&.v\fP"
.br
.ti -1c
.RI "\fBgraphing\&.e\fP"
.br
.ti -1c
.RI "\fBgraphing\&.line\fP = edges_file\&.readline()"
.br
.ti -1c
.RI "\fBgraphing\&.x\fP"
.br
.ti -1c
.RI "\fBgraphing\&.y\fP"
.br
.ti -1c
.RI "\fBgraphing\&.shape\fP = nx\&.spring_layout(DG)"
.br
.ti -1c
.RI "dictionary \fBgraphing\&.options\fP"
.br
.ti -1c
.RI "\fBgraphing\&.pos\fP"
.br
.ti -1c
.RI "\fBgraphing\&.comp_graph\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBgraphing\&.colors\fP = np\&.array([])"
.br
.ti -1c
.RI "int \fBgraphing\&.c\fP = 0"
.br
.ti -1c
.RI "\fBgraphing\&.s\fP = scc\&.readlines()"
.br
.ti -1c
.RI "\fBgraphing\&.V\fP = list(map(int, line\&.split()))"
.br
.ti -1c
.RI "\fBgraphing\&.sub\fP = DG\&.subgraph(V)"
.br
.ti -1c
.RI "\fBgraphing\&.cmap\fP"
.br
.ti -1c
.RI "\fBgraphing\&.node_color\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment 1 from the source code\&.
