.TH "graphing" 3 "Thu Mar 12 2020" "Version 1" "DAA Assignment - 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphing
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdataset_name\fP = sys\&.argv[1]\&.split('/')[\-1][:\-4]"
.br
.ti -1c
.RI "\fBDG\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBv\fP"
.br
.ti -1c
.RI "\fBe\fP"
.br
.ti -1c
.RI "\fBline\fP = edges_file\&.readline()"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBshape\fP = nx\&.spring_layout(\fBDG\fP)"
.br
.ti -1c
.RI "dictionary \fBoptions\fP"
.br
.ti -1c
.RI "\fBcomp_graph\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBcolors\fP = np\&.array([])"
.br
.ti -1c
.RI "int \fBc\fP = 0"
.br
.ti -1c
.RI "\fBs\fP = scc\&.readlines()"
.br
.ti -1c
.RI "\fBV\fP = list(map(int, line\&.split()))"
.br
.ti -1c
.RI "\fBsub\fP = DG\&.subgraph(\fBV\fP)"
.br
.ti -1c
.RI "\fBlabels\fP = dict(zip(comp_graph\&.nodes, list(map(str, comp_graph\&.nodes))))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int graphing\&.c = 0"

.PP
Definition at line 44 of file graphing\&.py\&.
.SS "graphing\&.colors = np\&.array([])"

.PP
Definition at line 43 of file graphing\&.py\&.
.SS "graphing\&.comp_graph = nx\&.DiGraph()"

.PP
Definition at line 42 of file graphing\&.py\&.
.SS "graphing\&.dataset_name = sys\&.argv[1]\&.split('/')[\-1][:\-4]"

.PP
Definition at line 10 of file graphing\&.py\&.
.SS "graphing\&.DG = nx\&.DiGraph()"

.PP
Definition at line 13 of file graphing\&.py\&.
.SS "graphing\&.e"

.PP
Definition at line 17 of file graphing\&.py\&.
.SS "graphing\&.labels = dict(zip(comp_graph\&.nodes, list(map(str, comp_graph\&.nodes))))"

.PP
Definition at line 57 of file graphing\&.py\&.
.SS "graphing\&.line = edges_file\&.readline()"

.PP
Definition at line 19 of file graphing\&.py\&.
.SS "dictionary graphing\&.options"
\fBInitial value:\fP
.PP
.nf
1 =  {
2     'node_size': 20,
3     'width': 0\&.1,
4     'alpha':0\&.6,
5     'edge_color': '#333333',
6     'pos':shape
7 }
.fi
.PP
Definition at line 26 of file graphing\&.py\&.
.SS "graphing\&.s = scc\&.readlines()"

.PP
Definition at line 46 of file graphing\&.py\&.
.SS "graphing\&.shape = nx\&.spring_layout(\fBDG\fP)"

.PP
Definition at line 25 of file graphing\&.py\&.
.SS "graphing\&.sub = DG\&.subgraph(\fBV\fP)"

.PP
Definition at line 51 of file graphing\&.py\&.
.SS "graphing\&.v"

.PP
Definition at line 17 of file graphing\&.py\&.
.SS "graphing\&.V = list(map(int, line\&.split()))"

.PP
Definition at line 49 of file graphing\&.py\&.
.SS "graphing\&.x"

.PP
Definition at line 22 of file graphing\&.py\&.
.SS "graphing\&.y"

.PP
Definition at line 22 of file graphing\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment - 1 from the source code\&.
