.TH "graphing" 3 "Wed Mar 11 2020" "Version 1" "DAA Assignment - 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphing
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDG\fP = nx\&.DiGraph()"
.br
.ti -1c
.RI "\fBv\fP"
.br
.ti -1c
.RI "\fBe\fP"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "dictionary \fBoptions\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "graphing\&.DG = nx\&.DiGraph()"

.PP
Definition at line 5 of file graphing\&.py\&.
.SS "graphing\&.e"

.PP
Definition at line 8 of file graphing\&.py\&.
.SS "dictionary graphing\&.options"
\fBInitial value:\fP
.PP
.nf
1 =  {
2     'node_size': 10,
3     'width': 0\&.01,
4     'edge_color': 'gray',
5     'alpha':0\&.5
6 }
.fi
.PP
Definition at line 13 of file graphing\&.py\&.
.SS "graphing\&.v"

.PP
Definition at line 8 of file graphing\&.py\&.
.SS "graphing\&.x"

.PP
Definition at line 10 of file graphing\&.py\&.
.SS "graphing\&.y"

.PP
Definition at line 10 of file graphing\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment - 1 from the source code\&.
