.TH "src/kosaraju_algorithm.cpp" 3 "Thu Mar 12 2020" "Version 1" "DAA Assignment - 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kosaraju_algorithm.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "This Program is the Implementation of \fBKosaraju Algorithm\fP\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "This is the main function which initializes object instance of graph class We build the graph by calling \fBGraph\fP class methods and by using \fBtopological sorting\fP we traverse on vertices We build the reverse of graph and check whether both DFS traversal results in same vertex for entire graph\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
This is the main function which initializes object instance of graph class We build the graph by calling \fBGraph\fP class methods and by using \fBtopological sorting\fP we traverse on vertices We build the reverse of graph and check whether both DFS traversal results in same vertex for entire graph\&. 
.PP
\fBReturns:\fP
.RS 4
nothing is returned\&. the result is just printed 
.RE
.PP
\fBSee also:\fP
.RS 4
reverseGraph() topological_sort() 
.RE
.PP
\fBNote:\fP
.RS 4
We have used \fIhigh_resolution_clock\fP for finding the time taken for the entire program to run\&. 
.RE
.PP
\fBAttention:\fP
.RS 4
No loops are allowed for the graph 
.RE
.PP

.PP
Definition at line 171 of file kosaraju_algorithm\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment - 1 from the source code\&.
