.TH "/home/badri/Desktop/subjects/CS F364/assign/assign1/map1.cpp" 3 "Sun Feb 23 2020" "Version 1" "DAA Assign-1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/badri/Desktop/subjects/CS F364/assign/assign1/map1.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "This Program is the Implementation of \fBKosaraju Algorithm\fP\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assign-1 from the source code\&.
