.TH "md__e_1__projects__d_a_a__assignments_assign1_doc1_doc_pages_page_one" 3 "Fri Mar 13 2020" "DAA Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__e_1__projects__d_a_a__assignments_assign1_doc1_doc_pages_page_one \- Results 
Results Produced
.PP
Dataset Results Kosaraju's Algorithm (Time taken) Divide and Conquer Algorithm(Time taken)  1) Test_1 Nodes: 1005
.br
Edges :10000
.br
num of scc :3 0\&.021s 0\&.001s  2) email-EU-core Nodes: 1005
.br
Edges :25571
.br
num of scc :203 0\&.129s 0\&.013962s  3) Wiki-Vote Nodes: 7115
.br
Edges :103689
.br
num of scc :5816 0\&.665s 7\&.07455s  4) p2p-Gnutella04 Nodes: 10876
.br
Edges :39994
.br
num of scc :6560 0\&.316s 12\&.6027s  5) soc-Epinions1 Nodes: 75879
.br
Edges :508837
.br
num of scc :42176 4\&.174s 668\&.653s  
.SS "Graphs"
Dataset Directed \fBGraph\fP (combined) Strongly Connected Components  1) test1 dataset    2) test2 dataset    3) test3 dataset    4) test4 dataset    5) email-Eu-core Dataset    6) Wiki-Vote Dataset    7) email-Eu-core Dataset    8) email-Eu-core Dataset    9) email-Eu-core Dataset    
