.TH "md_doc_doc_pages_page_one" 3 "Tue Apr 21 2020" "DAA Assignment 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_doc_doc_pages_page_one \- Results 
Results Produced
.PP
Dataset Results Kosaraju's Algorithm (Time taken) Divide and Conquer Algorithm(Time taken)  1) test1 Nodes: 8
.br
Edges: 11
.br
num of scc: 3 0\&.013s 0\&.001s  2) test2 Nodes: 9
.br
Edges: 12
.br
num of scc: 9 0\&.018s 0\&.001s  3) test3 Nodes: 13
.br
Edges: 15
.br
num of scc: 4 0\&.007s 0\&.001s  4) test4 Nodes: 9
.br
Edges: 11
.br
num of scc: 2 0\&.007s 0\&.001s  5) email-EU-core Nodes: 1005
.br
Edges: 25571
.br
num of scc: 203 0\&.129s 0\&.013962s  6) Wiki-Vote Nodes: 7115
.br
Edges: 103689
.br
num of scc: 5816 0\&.665s 7\&.07455s  7) p2p-Gnutella04 Nodes: 10876
.br
Edges: 39994
.br
num of scc: 6560 0\&.316s 12\&.6027s  8) soc-Epinions1 Nodes: 75879
.br
Edges: 508837
.br
num of scc: 42176 4\&.174s 668\&.653s  
.SS "Graphs"
Dataset Directed \fBGraph\fP (combined) Strongly Connected Components  1) test1    2) test2    3) test3    4) test4    5) email-Eu-core    6) Wiki-Vote    7) p2p-Gnutella04    
