.TH "/home/badri/Desktop/subjects/CS F364/assign/assign1/doc_pages/page_one.md" 3 "Sun Feb 23 2020" "Version 1" "DAA Assign-1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/badri/Desktop/subjects/CS F364/assign/assign1/doc_pages/page_one.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assign-1 from the source code\&.
