.TH "subsystem1" 3 "Sun Feb 23 2020" "Version 1" "DAA Assign-1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subsystem1Strongly Connected Components 
 \- \fBSubSubSystem 1\fP
.SH "Section 1"
.PP
When a directed graph vertices both reach each other then they are called strongly connected components\&.
.SH "Section 2"
.PP
\fBGraph\fP is basically a collection of vertices with connections
.SS "Sub Section 1"
Directed graph has directed edges
.PP
Here is an Image :
.PP
 
