.TH "src/ford-fulkerson.cpp" 3 "Fri Apr 24 2020" "DAA Assignment 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ford-fulkerson.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <sys/resource\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBipartiteMatching\fP ()"
.br
.RI "This function implements bipartite matching using ford-fulkerson algorithm\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "This is the main function\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBBipar\fP = 0"
.br
.ti -1c
.RI "int \fBnVSet1\fP =0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BipartiteMatching ()"

.PP
This function implements bipartite matching using ford-fulkerson algorithm\&. The input is used to construct the residual graph (Res) and then fordfulkerson() function is run on it\&.
.PP
\fBReturns\fP
.RS 4
none\&. 
.RE
.PP
\fBSee also\fP
.RS 4
fordFulkerson() 
.br
 
.RE
.PP

.SS "int main ()"

.PP
This is the main function\&. A residual graph is constructed using the data from input\&.
.PP
\fBReturns\fP
.RS 4
integer, 0\&. 
.RE
.PP
\fBSee also\fP
.RS 4
fordFulkerson() \fBBipartiteMatching()\fP 
.RE
.PP
\fBNote\fP
.RS 4
We have used \fIhigh_resolution_clock\fP for finding the time taken for the entire program to run\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int Bipar = 0"

.SS "int nVSet1 =0"

.SH "Author"
.PP 
Generated automatically by Doxygen for DAA Assignment 2 from the source code\&.
